# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadkast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='broadkast.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62roadkast.proto\">\n\rSelectorQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"X\n\x11\x44iscoveredService\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x18\n\x10instance_address\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\"\x90\x02\n\x17ServiceDiscoveryRequest\x12\x13\n\x06method\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x19\n\x0cservice_port\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\'\n\x0f\x66ield_selectors\x18\x05 \x03(\x0b\x32\x0e.SelectorQuery\x12\'\n\x0flabel_selectors\x18\x06 \x03(\x0b\x32\x0e.SelectorQuery\x12\x1b\n\x0eis_new_service\x18\x07 \x01(\x08H\x02\x88\x01\x01\x42\t\n\x07_methodB\x0f\n\r_service_portB\x11\n\x0f_is_new_service\"q\n\x18ServiceDiscoveryResponse\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12%\n\tinstances\x18\x02 \x03(\x0b\x32\x12.DiscoveredService\x12\x18\n\x10\x64iscovered_count\x18\x03 \x01(\x05\"i\n\x10KubeConfigUpdate\x12\x17\n\x0f\x63onfig_filepath\x18\x01 \x01(\t\x12\x16\n\x0e\x63onfig_context\x18\x02 \x01(\t\x12\x16\n\tnamespace\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_namespace\"\x81\x01\n\x18KubeConfigUpdateResponse\x12\x17\n\x0f\x63onfig_filepath\x18\x01 \x01(\t\x12\x16\n\x0e\x63onfig_context\x18\x02 \x01(\t\x12\x16\n\tnamespace\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06status\x18\x04 \x01(\tB\x0c\n\n_namespace2\xa2\x01\n\x0f\x42roadkastServer\x12\x45\n\x13UpdateClusterConfig\x12\x11.KubeConfigUpdate\x1a\x19.KubeConfigUpdateResponse\"\x00\x12H\n\x0f\x44iscoverService\x12\x18.ServiceDiscoveryRequest\x1a\x19.ServiceDiscoveryResponse\"\x00\x62\x06proto3'
)




_SELECTORQUERY = _descriptor.Descriptor(
  name='SelectorQuery',
  full_name='SelectorQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SelectorQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operator', full_name='SelectorQuery.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SelectorQuery.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=81,
)


_DISCOVEREDSERVICE = _descriptor.Descriptor(
  name='DiscoveredService',
  full_name='DiscoveredService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='DiscoveredService.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_address', full_name='DiscoveredService.instance_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='DiscoveredService.instance_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=171,
)


_SERVICEDISCOVERYREQUEST = _descriptor.Descriptor(
  name='ServiceDiscoveryRequest',
  full_name='ServiceDiscoveryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='ServiceDiscoveryRequest.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='ServiceDiscoveryRequest.service_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ServiceDiscoveryRequest.namespace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_port', full_name='ServiceDiscoveryRequest.service_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_selectors', full_name='ServiceDiscoveryRequest.field_selectors', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label_selectors', full_name='ServiceDiscoveryRequest.label_selectors', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_new_service', full_name='ServiceDiscoveryRequest.is_new_service', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_method', full_name='ServiceDiscoveryRequest._method',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_service_port', full_name='ServiceDiscoveryRequest._service_port',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_new_service', full_name='ServiceDiscoveryRequest._is_new_service',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=174,
  serialized_end=446,
)


_SERVICEDISCOVERYRESPONSE = _descriptor.Descriptor(
  name='ServiceDiscoveryResponse',
  full_name='ServiceDiscoveryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='ServiceDiscoveryResponse.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instances', full_name='ServiceDiscoveryResponse.instances', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='discovered_count', full_name='ServiceDiscoveryResponse.discovered_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=561,
)


_KUBECONFIGUPDATE = _descriptor.Descriptor(
  name='KubeConfigUpdate',
  full_name='KubeConfigUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_filepath', full_name='KubeConfigUpdate.config_filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config_context', full_name='KubeConfigUpdate.config_context', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='KubeConfigUpdate.namespace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_namespace', full_name='KubeConfigUpdate._namespace',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=563,
  serialized_end=668,
)


_KUBECONFIGUPDATERESPONSE = _descriptor.Descriptor(
  name='KubeConfigUpdateResponse',
  full_name='KubeConfigUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_filepath', full_name='KubeConfigUpdateResponse.config_filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config_context', full_name='KubeConfigUpdateResponse.config_context', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='KubeConfigUpdateResponse.namespace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='KubeConfigUpdateResponse.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_namespace', full_name='KubeConfigUpdateResponse._namespace',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=671,
  serialized_end=800,
)

_SERVICEDISCOVERYREQUEST.fields_by_name['field_selectors'].message_type = _SELECTORQUERY
_SERVICEDISCOVERYREQUEST.fields_by_name['label_selectors'].message_type = _SELECTORQUERY
_SERVICEDISCOVERYREQUEST.oneofs_by_name['_method'].fields.append(
  _SERVICEDISCOVERYREQUEST.fields_by_name['method'])
_SERVICEDISCOVERYREQUEST.fields_by_name['method'].containing_oneof = _SERVICEDISCOVERYREQUEST.oneofs_by_name['_method']
_SERVICEDISCOVERYREQUEST.oneofs_by_name['_service_port'].fields.append(
  _SERVICEDISCOVERYREQUEST.fields_by_name['service_port'])
_SERVICEDISCOVERYREQUEST.fields_by_name['service_port'].containing_oneof = _SERVICEDISCOVERYREQUEST.oneofs_by_name['_service_port']
_SERVICEDISCOVERYREQUEST.oneofs_by_name['_is_new_service'].fields.append(
  _SERVICEDISCOVERYREQUEST.fields_by_name['is_new_service'])
_SERVICEDISCOVERYREQUEST.fields_by_name['is_new_service'].containing_oneof = _SERVICEDISCOVERYREQUEST.oneofs_by_name['_is_new_service']
_SERVICEDISCOVERYRESPONSE.fields_by_name['instances'].message_type = _DISCOVEREDSERVICE
_KUBECONFIGUPDATE.oneofs_by_name['_namespace'].fields.append(
  _KUBECONFIGUPDATE.fields_by_name['namespace'])
_KUBECONFIGUPDATE.fields_by_name['namespace'].containing_oneof = _KUBECONFIGUPDATE.oneofs_by_name['_namespace']
_KUBECONFIGUPDATERESPONSE.oneofs_by_name['_namespace'].fields.append(
  _KUBECONFIGUPDATERESPONSE.fields_by_name['namespace'])
_KUBECONFIGUPDATERESPONSE.fields_by_name['namespace'].containing_oneof = _KUBECONFIGUPDATERESPONSE.oneofs_by_name['_namespace']
DESCRIPTOR.message_types_by_name['SelectorQuery'] = _SELECTORQUERY
DESCRIPTOR.message_types_by_name['DiscoveredService'] = _DISCOVEREDSERVICE
DESCRIPTOR.message_types_by_name['ServiceDiscoveryRequest'] = _SERVICEDISCOVERYREQUEST
DESCRIPTOR.message_types_by_name['ServiceDiscoveryResponse'] = _SERVICEDISCOVERYRESPONSE
DESCRIPTOR.message_types_by_name['KubeConfigUpdate'] = _KUBECONFIGUPDATE
DESCRIPTOR.message_types_by_name['KubeConfigUpdateResponse'] = _KUBECONFIGUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SelectorQuery = _reflection.GeneratedProtocolMessageType('SelectorQuery', (_message.Message,), {
  'DESCRIPTOR' : _SELECTORQUERY,
  '__module__' : 'broadkast_pb2'
  # @@protoc_insertion_point(class_scope:SelectorQuery)
  })
_sym_db.RegisterMessage(SelectorQuery)

DiscoveredService = _reflection.GeneratedProtocolMessageType('DiscoveredService', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVEREDSERVICE,
  '__module__' : 'broadkast_pb2'
  # @@protoc_insertion_point(class_scope:DiscoveredService)
  })
_sym_db.RegisterMessage(DiscoveredService)

ServiceDiscoveryRequest = _reflection.GeneratedProtocolMessageType('ServiceDiscoveryRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEDISCOVERYREQUEST,
  '__module__' : 'broadkast_pb2'
  # @@protoc_insertion_point(class_scope:ServiceDiscoveryRequest)
  })
_sym_db.RegisterMessage(ServiceDiscoveryRequest)

ServiceDiscoveryResponse = _reflection.GeneratedProtocolMessageType('ServiceDiscoveryResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEDISCOVERYRESPONSE,
  '__module__' : 'broadkast_pb2'
  # @@protoc_insertion_point(class_scope:ServiceDiscoveryResponse)
  })
_sym_db.RegisterMessage(ServiceDiscoveryResponse)

KubeConfigUpdate = _reflection.GeneratedProtocolMessageType('KubeConfigUpdate', (_message.Message,), {
  'DESCRIPTOR' : _KUBECONFIGUPDATE,
  '__module__' : 'broadkast_pb2'
  # @@protoc_insertion_point(class_scope:KubeConfigUpdate)
  })
_sym_db.RegisterMessage(KubeConfigUpdate)

KubeConfigUpdateResponse = _reflection.GeneratedProtocolMessageType('KubeConfigUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _KUBECONFIGUPDATERESPONSE,
  '__module__' : 'broadkast_pb2'
  # @@protoc_insertion_point(class_scope:KubeConfigUpdateResponse)
  })
_sym_db.RegisterMessage(KubeConfigUpdateResponse)



_BROADKASTSERVER = _descriptor.ServiceDescriptor(
  name='BroadkastServer',
  full_name='BroadkastServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=803,
  serialized_end=965,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateClusterConfig',
    full_name='BroadkastServer.UpdateClusterConfig',
    index=0,
    containing_service=None,
    input_type=_KUBECONFIGUPDATE,
    output_type=_KUBECONFIGUPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DiscoverService',
    full_name='BroadkastServer.DiscoverService',
    index=1,
    containing_service=None,
    input_type=_SERVICEDISCOVERYREQUEST,
    output_type=_SERVICEDISCOVERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROADKASTSERVER)

DESCRIPTOR.services_by_name['BroadkastServer'] = _BROADKASTSERVER

# @@protoc_insertion_point(module_scope)
